spring:
  application:
    name: ecommerce-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db?TimeZone=Asia/Kolkata
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}